### ISSUE TITLE
i am trying to build my project in Release and I am up with this issue 

### ISSUE THREAD

**Issue by ronakshethia** [enisn/Xamarin.Forms.InputKit#103]
Severity	Code	Description	Project	File	Line	Suppression State
Error		The "LinkAssemblies" task failed unexpectedly.
Mono.Linker.MarkException: Error processing method: 'System.Boolean Plugin.InputKit.Shared.Controls.AdvancedEntry::get_IsAnnotated()' in assembly: 'Plugin.InputKit.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.String[] System.String::Split(System.Char,System.StringSplitOptions)
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessEntireQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	HealthMobile.Android			

could u please help me this issue how can i solve this i am using version 2.3.6.1

**Comment by enisn** [comment]
I think this is almost same with #96

**Comment by enisn** [comment]
I've investigated that, it's not same with #96 

That problem occours from AdvancedEntry's IsAnnotated property. That was using string methods to check Validation. after **v3** it converted to Regex check. 

If you are not able to Migrate your project to V3 you can try [this solution](https://github.com/enisn/Xamarin.Forms.InputKit/issues/75#issuecomment-467918443)

**Comment by enisn** [comment]
I've just released a version for V2 users which is [v.2.3.9](https://github.com/enisn/Xamarin.Forms.InputKit/releases/tag/v.2.3.9) 

@ronakshethia  Can you try that version if it works or not?

**Comment by ronakshethia** [comment]
@enisn  i got my problem solved by updating xamarin forms and then adding init to platforms but now i am facing this Issue 

Severity	Code	Description	Project	File	Line	Suppression State
Error		The "LinkAssemblies" task failed unexpectedly.
Mono.Linker.MarkException: Error processing method: 'System.Boolean Plugin.InputKit.Shared.Controls.AutoCompleteEntry/<>c__DisplayClass6_0::<GetInputEntry>b__1(System.String)' in assembly: 'Plugin.InputKit.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Boolean System.String::Contains(System.String,System.StringComparison)
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessEntireQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	HealthMobile.Android			


do u have any idea how can i solve this ?

**Comment by enisn** [comment]
That is same with #96 now.
I'm working on it

**Comment by enisn** [comment]
Now, it's duplicated issue. Just follow #96 There is a pre-release which is v3.0.4-pre1, If problem continues, add comment to #96
