### ISSUE TITLE
Can't resolve the reference 'System.Boolean System.String::Contains(System.String,System.StringComparison)', referenced from the method 'System.Boolean Plugin.InputKit.Shared.Controls.AutoCompleteEntry

### ISSUE THREAD

**Issue by HelenMamalaki** [enisn/Xamarin.Forms.InputKit#96]
**Describe the bug**
I'm using a hosted build on Azure DevOps to build Android and iOS app in release mode but for iOS I am getting the following error.  I am using v3.0.2 of the Plugin. Error is similar to https://github.com/enisn/Xamarin.Forms.InputKit/issues/87 but it has been closed down.

Can't resolve the reference 'System.Boolean System.String::Contains(System.String,System.StringComparison)', referenced from the method 'System.Boolean Plugin.InputKit.Shared.Controls.AutoCompleteEntry/<>c__DisplayClass6_0::b__1(System.String)' in 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. [/Users/vsts/agent/2.147.1/work/1/s/App/App/App.iOS/App.iOS.csproj]
--
**To Reproduce**
I am still trying to figure out how to reproduce locally. I only get the problem on the automated build host. Sorry.

Edit: In trying to reproduce locally, I have tried with Android in Release mode and get the following error: I have tried uninstalling, reinstalling, deleting bin + obj folders. Nothing works.

The "LinkAssemblies" task failed unexpectedly.
Mono.Linker.MarkException: Error processing method: 'System.Boolean Plugin.InputKit.Shared.Controls.AutoCompleteEntry/<>c__DisplayClass6_0::<GetInputEntry>b__1(System.String)' in assembly: 'Plugin.InputKit.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Boolean System.String::Contains(System.String,System.StringComparison)
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	NGT.Android

**Comment by enisn** [comment]
Can you try pre-release version of  [v3.0.4-pre1](https://github.com/enisn/Xamarin.Forms.InputKit/releases/tag/v.3.0.4-pre1) if it works or not?

Still I'm working on it.

**Comment by ronakshethia** [comment]
@enisn  i am to build in release with this new pre-release version thanks

**Comment by enisn** [comment]
After @HelenMamalaki 's answer, I'll merge that feature with new version and release it if it works.

**Comment by HelenMamalaki** [comment]
> After @HelenMamalaki 's answer, I'll merge that feature with new version and release it if it works.

Hi, it works in the latest package, thank you!!
